name: Vagrant up
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
  provision:
    runs-on:
      - self-hosted
      - Linux
      - vagrant
    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: ./ci/test-pr.sh
